
name = "pwa-media-sets"
pages_build_output_dir = "."

[[ d1_databases ]]
binding = "DB"              # used in functions code as env.DB
database_name = "pwa_db"
database_id = "ab123cde-4567-890f-gh12-ijklmn345opq"
[[ r2_buckets ]]
binding = "MEDIA"           # used in functions code as env.MEDIA
bucket_name = "pwa-media-bucket"  # create in Cloudflare R2

[vars]
# Optional: simple admin token for write routes (leave empty to disable)
ADMIN_TOKEN = ""
